# Generated by Django 4.2.5 on 2023-09-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal", models.CharField(max_length=10)),
                ("adresse", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=100)),
                ("pays", models.CharField(max_length=100)),
                ("continent", models.CharField(max_length=100)),
                ("localisation", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Decideur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("poste", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("numero1", models.CharField(max_length=20)),
                ("numero2", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Societe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("secteur", models.CharField(max_length=100)),
                ("emails", models.EmailField(max_length=100)),
                ("numero1", models.CharField(max_length=20)),
                ("numero2", models.CharField(max_length=20)),
                ("numero3", models.CharField(max_length=20)),
                ("fixe", models.CharField(max_length=20)),
                ("adresse", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=100)),
                ("pays", models.CharField(max_length=100)),
                ("continent", models.CharField(max_length=100)),
                ("localisation", models.CharField(max_length=255)),
                ("demarchage_emails", models.EmailField(max_length=100)),
                ("demarchage_numero1", models.CharField(max_length=20)),
                ("demarchage_numero2", models.CharField(max_length=20)),
                ("demarchage_numero3", models.CharField(max_length=20)),
                (
                    "adresse_postal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.adresse"
                    ),
                ),
                (
                    "decideur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.decideur"
                    ),
                ),
            ],
        ),
    ]
