# Generated by Django 4.2.5 on 2023-10-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_societe_adresse_remove_societe_continent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decideur",
            name="sexe",
            field=models.CharField(default="king", max_length=10),
            preserve_default=False,
        ),
    ]
