# Generated by Django 4.2.5 on 2023-10-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_decideur_sexe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="societe",
            name="adresses",
        ),
        migrations.RemoveField(
            model_name="societe",
            name="decideurs",
        ),
        migrations.RemoveField(
            model_name="societe",
            name="numero1",
        ),
        migrations.RemoveField(
            model_name="societe",
            name="numero2",
        ),
        migrations.RemoveField(
            model_name="societe",
            name="numero3",
        ),
        migrations.AddField(
            model_name="societe",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="continent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="demarchage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="societe",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="localisation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="pays",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="poste",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="prenom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="sexe",
            field=models.CharField(
                blank=True,
                choices=[("masculin", "Masculin"), ("feminin", "Féminin")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="societe",
            name="site_web",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="societe",
            field=models.CharField(default="societe", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="societe",
            name="tel1",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="tel2",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="telephone1",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="telephone2",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="telephone3",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="societe",
            name="ville",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="societe",
            name="adresse_postal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="societe",
            name="demarchage_emails",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="societe",
            name="demarchage_numero1",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="societe",
            name="demarchage_numero2",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="societe",
            name="demarchage_numero3",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="societe",
            name="emails",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="societe",
            name="fixe",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="societe",
            name="nom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="societe",
            name="secteur",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Adresse",
        ),
        migrations.DeleteModel(
            name="Decideur",
        ),
    ]
