# Generated by Django 4.2.5 on 2023-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_remove_societe_adresses_remove_societe_decideurs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="societe",
            name="demarchage_emails",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
