# Generated by Django 4.2.5 on 2023-10-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_societe_demarchage_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="societe",
            name="demarchage_emails",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
