# Generated by Django 4.2.5 on 2023-09-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal", models.CharField(max_length=10)),
                ("adresse", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("metiers", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("sexe", models.CharField(max_length=10)),
                ("adresse", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=100)),
                ("numero1", models.CharField(max_length=20)),
                ("numero2", models.CharField(max_length=20)),
                ("numero3", models.CharField(max_length=20)),
                ("demarchage_numero1", models.CharField(max_length=20)),
                ("demarchage_numero2", models.CharField(max_length=20)),
                ("demarchage_numero3", models.CharField(max_length=20)),
                (
                    "adresse_postal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp_personnes.adresse",
                    ),
                ),
            ],
        ),
    ]
