# Generated by Django 4.2.5 on 2023-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp_personnes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personne",
            name="adresse",
        ),
        migrations.RemoveField(
            model_name="personne",
            name="adresse_postal",
        ),
        migrations.RemoveField(
            model_name="personne",
            name="ville",
        ),
        migrations.AddField(
            model_name="personne",
            name="adresses",
            field=models.ManyToManyField(to="myapp_personnes.adresse"),
        ),
    ]
