# Generated by Django 4.2.5 on 2023-10-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp_personnes", "0002_remove_personne_adresse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adresse",
            name="continent",
            field=models.CharField(default="Afrique", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adresse",
            name="pays",
            field=models.CharField(default="Benin", max_length=100),
            preserve_default=False,
        ),
    ]
