# Generated by Django 4.2.5 on 2023-10-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp_personnes", "0003_adresse_continent_adresse_pays"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personne",
            name="adresses",
        ),
        migrations.RemoveField(
            model_name="personne",
            name="demarchage_numero1",
        ),
        migrations.RemoveField(
            model_name="personne",
            name="demarchage_numero2",
        ),
        migrations.RemoveField(
            model_name="personne",
            name="demarchage_numero3",
        ),
        migrations.RemoveField(
            model_name="personne",
            name="metiers",
        ),
        migrations.RemoveField(
            model_name="personne",
            name="numero1",
        ),
        migrations.RemoveField(
            model_name="personne",
            name="numero2",
        ),
        migrations.RemoveField(
            model_name="personne",
            name="numero3",
        ),
        migrations.AddField(
            model_name="personne",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="continent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="demarchage_tel1",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="demarchage_tel2",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="demarchage_tel3",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="pays",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="postal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="poste",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="tel1",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="tel2",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="tel3",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="personne",
            name="ville",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personne",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personne",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personne",
            name="sexe",
            field=models.CharField(
                blank=True,
                choices=[("masculin", "Masculin"), ("feminin", "Féminin")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Adresse",
        ),
    ]
